FROM python:3

RUN mkdir code

WORKDIR code

RUN git clone -b feature/logging https://github.com/IntegrCiTy/obnl.git
RUN pip install --no-cache-dir -r obnl/requirements.txt

RUN cd obnl && python setup.py install

RUN git clone https://github.com/IntegrCiTy/DemoGA.git

ENTRYPOINT ["python", "obnl/obnl/server.py"] 

# docker run -it --rm integrcity/orchestrator <IP_RABBIT> DemoGA/data/sce.json DemoGA/data/run.json
