FROM continuumio/miniconda3

# ImportError: libgfortran.so.3
RUN apt-get install -y libgfortran3
# https://github.com/ContinuumIO/anaconda-issues/issues/686 ?

RUN conda create --name ict-env python=3.5

RUN /bin/bash -c "source activate ict-env && conda install -y -c chria pyfmi=2.4"
RUN /bin/bash -c "source activate ict-env && pip install --ignore-installed -U setuptools"

RUN mkdir code
WORKDIR code

RUN git clone -b develop https://github.com/ppuertocrem/obnl.git
RUN /bin/bash -c "source activate ict-env && pip install --no-cache-dir -r obnl/requirements.txt"

RUN /bin/bash -c "source activate ict-env && cd obnl && python setup.py install"

RUN git clone https://github.com/IntegrCiTy/DemoGA.git
RUN /bin/bash -c "source activate ict-env && pip install --no-cache-dir -r DemoGA/requirements.txt"

ENV USER root

ENV ICT_FILE ""
ENV ICT_HOST ""

ENTRYPOINT ["/bin/bash", "-c", "source activate ict-env && python DemoGA/wrappers/${ICT_FILE} ${ICT_HOST}"]

# docker run -it --rm --env ICT_FILE=hp_central.py --env ICT_HOST=localhost? node
