FROM continuumio/miniconda3

# ImportError: libgfortran.so.3
RUN apt-get install -y libgfortran3
# https://github.com/ContinuumIO/anaconda-issues/issues/686 ?

RUN conda create --name ict-env python=3.5

RUN /bin/bash -c "source activate ict-env && conda install -y -c chria pyfmi=2.4"
RUN /bin/bash -c "source activate ict-env && pip install --ignore-installed -U setuptools"

RUN mkdir code
WORKDIR code

RUN git clone -b develop https://github.com/ppuertocrem/obnl.git
RUN /bin/bash -c "source activate ict-env && pip install --no-cache-dir -r obnl/requirements.txt"

RUN /bin/bash -c "source activate ict-env && cd obnl && python setup.py install"

RUN git clone https://github.com/IntegrCiTy/DemoGA.git
RUN /bin/bash -c "source activate ict-env && pip install --no-cache-dir -r DemoGA/requirements.txt"


RUN echo "import sys" >> DemoGA/wrappers/error.py
RUN echo "from common.node_fmu import NodeFMU" >> DemoGA/wrappers/error.py
RUN echo "print('NodeFMU imported !')" >> DemoGA/wrappers/error.py
RUN echo "print('ARG:', sys.argv[1])" >> DemoGA/wrappers/error.py

RUN echo "#!/bin/sh" >> entrypoint.sh
RUN echo "/bin/bash -c source activate ict-env" >> entrypoint.sh
RUN echo "python DemoGA/wrappers/error.py "$1""

RUN chmod +x entrypoint.sh

ENV USER root

# ENTRYPOINT ["/bin/bash", "-c", "source activate ict-env && python DemoGA/wrappers/hp_central.py"]
ENTRYPOINT ["/bin/bash", "-c", "./entrypoint.sh"]
