FROM ubuntu

USER root

# Configure environment
ENV SHELL=/bin/bash \
    NB_USER=ictuser \
    NB_UID=1000 \
    NB_GID=100

ENV HOME=/home/$NB_USER

ADD fix-permissions /usr/local/bin/fix-permissions
RUN chmod +x /usr/local/bin/fix-permissions

RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
	fix-permissions $HOME

USER $NB_USER

# Setup work directory for backward-compatibility
RUN mkdir /home/$NB_USER/work && \
	fix-permissions /home/$NB_USER

WORKDIR $HOME
