FROM python:3


RUN git clone -b feature/logging https://github.com/IntegrCiTy/obnl.git
WORKDIR obnl

RUN pip install --no-cache-dir -r requirements.txt

RUN python setup.py install

# Configure environment ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ENV SHELL=/bin/bash \
    NB_USER=ictuser \
    NB_UID=1000 \
    NB_GID=100

ENV HOME=/home/$NB_USER

ADD fix-permissions /usr/local/bin/fix-permissions
RUN chmod +x /usr/local/bin/fix-permissions

RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
	fix-permissions $HOME

USER $NB_USER

# Setup work directory for backward-compatibility
RUN mkdir /home/$NB_USER/work && \
	fix-permissions /home/$NB_USER

WORKDIR $HOME/work

ENTRYPOINT ["python", "obnl/server.py"] 

# docker run -it --rm -v $(pwd):/home/ictuser/work integrcity/orchestrator <IP_RABBIT> <SCENARIO.json> <CONFIG.json>
