FROM python:3

RUN mkdir code

WORKDIR code

RUN git clone -b develop https://github.com/IntegrCiTy/obnl.git
RUN pip install --no-cache-dir -r obnl/requirements.txt

RUN cd obnl && python setup.py install

RUN git clone https://github.com/IntegrCiTy/DemoGA.git

ENV ICT_RUN_FILE ""
ENV ICT_SCE_FILE ""
ENV ICT_HOST ""

ENTRYPOINT ["/usr/local/bin/python", "obnl/obnl/server.py", "${ICT_HOST}", "DemoGA/data/${ICT_RUN_FILE}", "DemoGA/data/${ICT_SCE_FILE}"]

# # docker run -it --rm --env ICT_RUN_FILE=run.json --env ICT_SCE_FILE=sce.json --env ICT_HOST=localhost? orch